<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Commodity Prices Index - Technical notes: commodity price index computation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Commodity Prices Index</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../doc_un/index.html"> 
<span class="menu-text">Documentation</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/chizapoth/un-commodity-prices"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#metadata" id="toc-metadata" class="nav-link active" data-scroll-target="#metadata">Metadata</a></li>
  <li><a href="#data-collection-and-processing" id="toc-data-collection-and-processing" class="nav-link" data-scroll-target="#data-collection-and-processing">Data collection and processing</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection">Data collection</a>
  <ul class="collapse">
  <li><a href="#world-bank" id="toc-world-bank" class="nav-link" data-scroll-target="#world-bank">World Bank</a></li>
  <li><a href="#imf" id="toc-imf" class="nav-link" data-scroll-target="#imf">IMF</a></li>
  <li><a href="#fao" id="toc-fao" class="nav-link" data-scroll-target="#fao">FAO</a></li>
  </ul></li>
  <li><a href="#merge" id="toc-merge" class="nav-link" data-scroll-target="#merge">Merge</a></li>
  </ul></li>
  <li><a href="#quality-checks" id="toc-quality-checks" class="nav-link" data-scroll-target="#quality-checks">Quality checks</a>
  <ul class="collapse">
  <li><a href="#fill-missing-period" id="toc-fill-missing-period" class="nav-link" data-scroll-target="#fill-missing-period">Fill missing period</a>
  <ul class="collapse">
  <li><a href="#manganese" id="toc-manganese" class="nav-link" data-scroll-target="#manganese">Manganese</a></li>
  <li><a href="#sunflower-oil" id="toc-sunflower-oil" class="nav-link" data-scroll-target="#sunflower-oil">Sunflower oil</a></li>
  <li><a href="#palm-kernel-oil" id="toc-palm-kernel-oil" class="nav-link" data-scroll-target="#palm-kernel-oil">Palm kernel oil</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#price-index-computation" id="toc-price-index-computation" class="nav-link" data-scroll-target="#price-index-computation">Price index computation</a>
  <ul class="collapse">
  <li><a href="#prepare-weights" id="toc-prepare-weights" class="nav-link" data-scroll-target="#prepare-weights">Prepare weights</a>
  <ul class="collapse">
  <li><a href="#weights" id="toc-weights" class="nav-link" data-scroll-target="#weights">Weights</a></li>
  <li><a href="#combine-weight-with-metadata" id="toc-combine-weight-with-metadata" class="nav-link" data-scroll-target="#combine-weight-with-metadata">Combine weight with metadata</a></li>
  <li><a href="#within-product-weights" id="toc-within-product-weights" class="nav-link" data-scroll-target="#within-product-weights">Within product weights</a></li>
  </ul></li>
  <li><a href="#compute-index" id="toc-compute-index" class="nav-link" data-scroll-target="#compute-index">Compute index</a>
  <ul class="collapse">
  <li><a href="#index-for-one-product-group" id="toc-index-for-one-product-group" class="nav-link" data-scroll-target="#index-for-one-product-group">Index for one product group</a></li>
  <li><a href="#index-for-other-groups" id="toc-index-for-other-groups" class="nav-link" data-scroll-target="#index-for-other-groups">Index for other groups</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Technical notes: commodity price index computation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This document contains the technical notes for the commodity price index computation. The R code in this document are consistent with <code>1_compute_validate_index.R</code>.</p>
<p>The index computation requires the following steps, which are explained in details in the next sections.</p>
<ol type="1">
<li>load raw data and process</li>
<li>missing data handling</li>
<li>compute index from merged dataset from the new source</li>
</ol>
<p>The validation and plots are recorded in graphics in the other reproducible document.</p>
<p>First you need to load necessary R packages and set the project directory. The directories are recommended to distinguish source code, metadata and data for validation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openxlsx)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>project_path <span class="ot">&lt;-</span> <span class="st">'~/Documents/GitHub/un-commodity-prices/deliverables/'</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># source the functions needed</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">paste0</span>(project_path, <span class="st">'rscripts/util.R'</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># set paths</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>read_path <span class="ot">&lt;-</span> <span class="fu">paste0</span>(project_path, <span class="st">'data/'</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>dir_metadata <span class="ot">&lt;-</span> <span class="st">'metadata/'</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>dir_datasource_2024 <span class="ot">&lt;-</span> <span class="st">'datasource_2024/'</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>dir_val <span class="ot">&lt;-</span> <span class="st">'validation/'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="metadata" class="level2">
<h2 class="anchored" data-anchor-id="metadata">Metadata</h2>
<p>First load the <strong>metadata</strong> that contains information for extracting the relevant columns from the international sources.</p>
<p>The content of metadata:</p>
<ul>
<li><code>index_sort</code>: 4-digits ID used to compute price index</li>
<li><code>series_id</code>: 8 digits ID for specific commodity</li>
<li><code>description_long</code>: detailed description of commodity for 2024 sources</li>
<li><code>unit_2024</code>: unit used as in the description (2024 sources). This might not be the same as in the 2025 sources.</li>
<li><code>data_source_2024_code</code>, <code>data_source_2024</code>: code and description for data sources used in 2024 version. For example, 5110 is World Bank Commodity markets.</li>
<li><code>data_source_2025_code</code>, <code>data_source_2025</code>: code and description for data sources used in 2025 version.</li>
<li><code>label_display</code>: commodity name, used for graphics</li>
<li><code>label_source_2025</code>: commodity name as in their 2025 data sources. It is important to match the correct names to the latest data.</li>
<li><code>check_two_sources</code>: indicator of whether the sources are switched from 2024 to 2025. If yes, then quality check graphics will be produced.</li>
<li><code>keep</code>: indicator of whether we keep the series in the price index computation.</li>
<li><code>within_product_weight</code>: weight for products that share the same <code>index_sort</code>. For now only applies to coffee and oil.</li>
<li><code>share_scale</code>: used only for computing products in the subgroups.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>metadata <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="fu">paste0</span>(read_path, dir_metadata, <span class="st">'commodity_metadata.xlsx'</span>), </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sheet =</span> <span class="st">'commodity'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(metadata, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  index_sort series_id description_short
1       1005 020100.01              beef
                                          description_long  unit_2024
1 Beef, Australia/New Zealand, frozen, CIF US ports ($/kg) usd_per_kg
  data_source_2024_code               data_source_2024 data_source_2025_code
1                  5110 World Bank - Commodity-markets                  5110
                data_source_2025 label_display label_source_2025
1 World Bank - Commodity-markets          Beef           Beef.**
  check_two_sources keep within_product_weight share_scale
1              &lt;NA&gt;  yes                     1           1</code></pre>
</div>
</div>
</section>
<section id="data-collection-and-processing" class="level1">
<h1>Data collection and processing</h1>
<p>In this step we gather the data from their original sources, then carry out some processing. The end result at this step is a data frame with all the commodity series ready to enter the computation.</p>
<section id="data-collection" class="level2">
<h2 class="anchored" data-anchor-id="data-collection">Data collection</h2>
<section id="world-bank" class="level3">
<h3 class="anchored" data-anchor-id="world-bank">World Bank</h3>
<p>We load the World Bank data from an URL (functional as of 2025.4.29)</p>
<p>Do some processing: convert the prices into numeric values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>wb_link <span class="ot">&lt;-</span> <span class="st">'https://thedocs.worldbank.org/en/doc/18675f1d1639c7a34d463f59263ba0a2-0050012025/related/CMO-Historical-Data-Monthly.xlsx'</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>wb_raw <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(wb_link, </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sheet =</span> <span class="st">"Monthly Prices"</span>, <span class="at">startRow =</span> <span class="dv">5</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print the column names</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>wb_var <span class="ot">&lt;-</span> <span class="fu">get_info_wb</span>(wb_raw)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># process the raw data</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># make the values numeric</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>wb <span class="ot">&lt;-</span> <span class="fu">process_data_wb</span>(<span class="at">data =</span> wb_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now select the relevant commodities, as defined by <strong>metadata</strong>. We choose the ones where <code>data_source_2025_code == 5110</code> (world bank), no missing (<code>!is.na(label_source_2025)</code> and <code>keep == 'yes'</code> to indicate whether it’s needed.</p>
<p>Please double check whether the variables are what we need!</p>
<p>Some of the labels might have special characters, hence we replace them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select relevant series</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># based on metadata</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># this also has to be within the wb scope</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>wb_info <span class="ot">&lt;-</span> <span class="fu">filter</span>(metadata, data_source_2025_code <span class="sc">==</span> <span class="dv">5110</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(label_source_2025) <span class="sc">&amp;</span> keep <span class="sc">==</span> <span class="st">'yes'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># process the labels to remove the special characters</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>wb_labels <span class="ot">&lt;-</span> wb_info<span class="sc">$</span>label_source_2025</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>wb_labels <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">','</span>, <span class="st">'.'</span>, wb_labels) <span class="co"># substitute the commas</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>wb_labels <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">'</span><span class="sc">\\</span><span class="st">*'</span>, <span class="st">'.'</span>, wb_labels) <span class="co"># substitute the star (careful since it's wildcard)</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>wb_labels <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">'%'</span>, <span class="st">'.'</span>, wb_labels) <span class="co"># substitute the commas</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>wb_labels</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Beef..."                 "Banana..US"             
 [3] "Coffee..Arabica"         "Coffee..Robusta"        
 [5] "Tea..Mombasa"            "Wheat..US.HRW"          
 [7] "Maize"                   "Rice..Thai.5."          
 [9] "Soybeans"                "Soybean.meal"           
[11] "Cotton..A.Index"         "Soybean.oil"            
[13] "Groundnut.oil..."        "Palm.oil"               
[15] "Sunflower.oil"           "Coconut.oil"            
[17] "Palm.kernel.oil"         "Sugar..world"           
[19] "Cocoa"                   "Fish.meal"              
[21] "Tobacco..US.import.u.v." "Phosphate.rock"         
[23] "Iron.ore..cfr.spot"      "Copper"                 
[25] "Nickel"                  "Aluminum"               
[27] "Lead"                    "Zinc"                   
[29] "Tin"                     "Silver"                 
[31] "Coal..Australian"        "Crude.oil..Brent"       
[33] "Crude.oil..Dubai"        "Natural.gas.index"      
[35] "Rubber..RSS3"            "Logs..Cameroon"         
[37] "Sawnwood..Malaysian"     "Plywood"                
[39] "Gold"                    "Platinum"               </code></pre>
</div>
</div>
<p>Above are the variable names that correspond to the world bank data file. Now we carry out the selection: keep <code>year</code>, <code>period</code>, <code>time</code>, <code>datetime</code> and the commodity labels.</p>
<p>Since some labels are long and have special characters, we set new names that are easier for coding.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select based on names</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>wb_narrow <span class="ot">&lt;-</span> <span class="fu">select</span>(wb, year, period, time, datetime, <span class="fu">all_of</span>(wb_labels))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># reset the colnames</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># colnames(wb_narrow)[5:ncol(wb_narrow)]</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(wb_narrow)[<span class="dv">5</span><span class="sc">:</span><span class="fu">ncol</span>(wb_narrow)] <span class="ot">&lt;-</span> wb_info<span class="sc">$</span>description_short</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(wb_narrow)[<span class="dv">5</span><span class="sc">:</span><span class="fu">ncol</span>(wb_narrow)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "beef"             "banana_us"        "coffee_arabica"   "coffee_robusta"  
 [5] "tea_mombasa"      "wheat_us"         "maize"            "rice"            
 [9] "soybeans"         "soybean_meal"     "cotton"           "soybean_oil"     
[13] "groundnut_oil"    "palm_oil"         "sunflower_oil"    "coconut_oil"     
[17] "palmkernel_oil"   "sugar"            "cocoa"            "fish_meal"       
[21] "tobacco"          "phosphate_rock"   "iron_ore"         "copper"          
[25] "nickel"           "aluminium"        "lead"             "zinc"            
[29] "tin"              "silver"           "coal"             "crude_oil_brent" 
[33] "crude_oil_dubai"  "naturalgas_index" "rubber_rss3"      "logs_cameroon"   
[37] "sawnwood"         "plywood"          "gold"             "platinum"        </code></pre>
</div>
</div>
</section>
<section id="imf" class="level3">
<h3 class="anchored" data-anchor-id="imf">IMF</h3>
<p>Carry out similar tasks for the IMF data.</p>
<p>One thing to note is that IMF data API is subject to change in the near future. Please double check if the link is still functional.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>imf_link <span class="ot">&lt;-</span> <span class="st">'https://www.imf.org/-/media/Files/Research/CommodityPrices/Monthly/external-data.ashx'</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># imf_raw &lt;- read_excel(paste0('YOUR_PATH', "imf.xls"))</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>imf_loc <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(imf_link, imf_loc)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># read from temporary path</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>imf_raw <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> imf_loc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `POILAPSP` -&gt; `POILAPSP...17`
• `POILAPSP` -&gt; `POILAPSP...45`
• `` -&gt; `...89`
• `` -&gt; `...90`
• `` -&gt; `...91`
• `` -&gt; `...92`
• `` -&gt; `...93`
• `` -&gt; `...94`
• `` -&gt; `...95`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check variables</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>imf_var <span class="ot">&lt;-</span> <span class="fu">get_info_imf</span>(imf_raw)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># View(imf_var)</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># process data, conver to numerics</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>imf <span class="ot">&lt;-</span> <span class="fu">process_data_imf</span>(imf_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The last few columns are a bit messy, we manually set the name for <strong>Manganese</strong>. Please double check if this is what you need!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># need to fill in Manganese</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>imf <span class="ot">&lt;-</span> <span class="fu">fill_imf_name</span>(<span class="at">data =</span> imf, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">keyword =</span> <span class="st">'Mang'</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">col_to_fill =</span> <span class="st">'...92'</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill_name =</span> <span class="st">'PMANG'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Select the variables defined in <strong>metadata</strong>: where <code>data_source_2025_code == 2311</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>imf_info <span class="ot">&lt;-</span> <span class="fu">filter</span>(metadata, data_source_2025_code <span class="sc">==</span> <span class="dv">2311</span> <span class="sc">&amp;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">!</span><span class="fu">is.na</span>(label_source_2025) <span class="sc">&amp;</span> keep <span class="sc">==</span> <span class="st">'yes'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>imf_info</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  index_sort series_id description_short
1       1010 030212.01       fish_salmon
2       1011 030613.01       shrimps_mex
3       3002 260200.02      manganese_99
4       2006 410100.01             hides
5       2004 510100.03         wool_fine
                                                                   description_long
1                        Salmon, fresh, fish-farm bred, export price, Norway ($/kg)
2                          Shrimps, brown, no. 1, shell-on, headless, Mexico ($/kg)
3     Manganese 99.7% electrolytic manganese flake, free market, in warehouse ($/t)
4 Cattle hides, US Chicago packer's heavy native steers, FOB shipping point (¢/lb.)
5                         Fine wool, 19 Micron, AWEX auction price, Australia ($/t)
      unit_2024 data_source_2024_code                 data_source_2024
1    usd_per_kg                  7801                Statistics Norway
2    usd_per_kg                  5110   World Bank - Commodity-markets
3 usd_per_tonne                  6801           Metal Bulletin Limited
4   cent_per_lb                  2311   IMF - Primary Commodity Prices
5 usd_per_tonne                  8001 Australian Wool Innovation (AWI)
  data_source_2025_code               data_source_2025      label_display
1                  2311 IMF - Primary Commodity Prices      Fish (Salmon)
2                  2311 IMF - Primary Commodity Prices Shrimps (Thailand)
3                  2311 IMF - Primary Commodity Prices     Manganese 99.7
4                  2311 IMF - Primary Commodity Prices              Hides
5                  2311 IMF - Primary Commodity Prices        Wool (fine)
  label_source_2025 check_two_sources keep within_product_weight share_scale
1             PSALM               yes  yes                     1           1
2             PSHRI              &lt;NA&gt;  yes                     1           1
3             PMANG               yes  yes                     1           1
4             PHIDE               yes  yes                     1           1
5            PWOOLF               yes  yes                     1           1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select relevant columns</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>imf_narrow <span class="ot">&lt;-</span> <span class="fu">select</span>(imf, year, datetime, <span class="fu">all_of</span>(imf_info<span class="sc">$</span>label_source_2025))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># reset name </span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(imf_narrow)[<span class="dv">3</span><span class="sc">:</span><span class="fu">ncol</span>(imf_narrow)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "PSALM"  "PSHRI"  "PMANG"  "PHIDE"  "PWOOLF"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(imf_narrow)[<span class="dv">3</span><span class="sc">:</span><span class="fu">ncol</span>(imf_narrow)] <span class="ot">&lt;-</span> imf_info<span class="sc">$</span>description_short</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fao" class="level3">
<h3 class="anchored" data-anchor-id="fao">FAO</h3>
<p>The mechanism is slightly different for FAO. First grab the name (<code>Jute</code>), then query it based on <code>uuid</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first get metadata</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>fpma_api <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">"https://fpma.fao.org/giews/v4/price_module/api/v1/FpmaSerieInternational/"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>fpma_raw <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(fpma_api<span class="sc">$</span>content))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># str(fpma_raw)</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>fpma_data <span class="ot">&lt;-</span> fpma_raw<span class="sc">$</span>results</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># get information for jute</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># do the same for other commodity if needed</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>jute_info <span class="ot">&lt;-</span> <span class="fu">filter</span>(fpma_data, <span class="fu">grepl</span>(<span class="st">'Jute'</span>, commodity_name))</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>jute_info</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  uuid iso3_country_code         country_name
1 5a272e65-e437-41c2-bcb0-f229dc14f47b               IPS INTERNATIONAL PRICES
                      periodicity market market_name market_info market_type
1 monthly, 2024-04-01, 2004-01-01   1750  Bangladesh                  Export
  admin_unit admin_unit2 commodity
1                             2711
                                                                 commodity_name
1 Jute BWD (f.o.b. Mongla, at sight)/from 2006 Jute BTD (f.o.b Bangladesh Port)
  commodity_info commodity_image commodity_code commodity_start_date
1                             NA      CMM530300                    1
  alternative_code alternative_name source
1                                      323
                                                                  source_name
1 Bangladesh Jute Mills Corporation/The Public Ledger/Wilhelm G. Clasen (WGC)
  source_url price_type_id price_type currency measure_unit measure_unit_label
1                       11     EXPORT      USD         3555              tonne
  conversion_factor
1             0.001</code></pre>
</div>
</div>
<p>We use the <code>uuid</code> to get the jute data. Double check the period where the data is available (it is only from 2004.1 to 2024.1).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>jute_raw <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="fu">paste0</span>(<span class="st">"https://fpma.fao.org/giews/v4/price_module/api/v1/FpmaSeriePrice/"</span>,jute_info<span class="sc">$</span>uuid,<span class="st">"/"</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>jute <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(jute_raw<span class="sc">$</span>content))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># only from 2004.1 to 2024.1</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(jute<span class="sc">$</span>datapoints, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id price_value price_value_real price_value_dollar conversion_factor
1 5070349         840               NA                840             0.001
2 5070348         780               NA                780             0.001
3 5070347         820               NA                820             0.001
        date periodicity
1 2024-04-01     monthly
2 2024-03-01     monthly
3 2024-02-01     monthly</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(jute<span class="sc">$</span>datapoints, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        id price_value price_value_real price_value_dollar conversion_factor
242 612508         245               NA                245             0.001
243 612507         245               NA                245             0.001
244 612506         230               NA                230             0.001
          date periodicity
242 2004-03-01     monthly
243 2004-02-01     monthly
244 2004-01-01     monthly</code></pre>
</div>
</div>
<p>Convert to proper format to prepare for merging.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>jute <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(jute<span class="sc">$</span>datapoints[, <span class="fu">c</span>(<span class="st">'date'</span>, <span class="st">'price_value_dollar'</span>)])</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(jute)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">'datetime'</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(jute)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">'jute'</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>jute<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(jute<span class="sc">$</span>datetime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="merge" class="level2">
<h2 class="anchored" data-anchor-id="merge">Merge</h2>
<p>We carry out a <strong>left_join</strong> on the three data sets. The keywords that we join by are the <strong>date times</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dcommodity <span class="ot">&lt;-</span> <span class="fu">left_join</span>(wb_narrow, imf_narrow) <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(jute)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(year, datetime)`
Joining with `by = join_by(datetime)`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dcommodity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "year"             "period"           "time"             "datetime"        
 [5] "beef"             "banana_us"        "coffee_arabica"   "coffee_robusta"  
 [9] "tea_mombasa"      "wheat_us"         "maize"            "rice"            
[13] "soybeans"         "soybean_meal"     "cotton"           "soybean_oil"     
[17] "groundnut_oil"    "palm_oil"         "sunflower_oil"    "coconut_oil"     
[21] "palmkernel_oil"   "sugar"            "cocoa"            "fish_meal"       
[25] "tobacco"          "phosphate_rock"   "iron_ore"         "copper"          
[29] "nickel"           "aluminium"        "lead"             "zinc"            
[33] "tin"              "silver"           "coal"             "crude_oil_brent" 
[37] "crude_oil_dubai"  "naturalgas_index" "rubber_rss3"      "logs_cameroon"   
[41] "sawnwood"         "plywood"          "gold"             "platinum"        
[45] "fish_salmon"      "shrimps_mex"      "manganese_99"     "hides"           
[49] "wool_fine"        "jute"            </code></pre>
</div>
</div>
</section>
</section>
<section id="quality-checks" class="level1">
<h1>Quality checks</h1>
<p>It can be very convenient to visualize the data missingness.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualise which series are missing</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>commodity_only <span class="ot">&lt;-</span> <span class="fu">select</span>(dcommodity, <span class="sc">-</span><span class="fu">c</span>(year, period, time, datetime))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vis_miss</span>(commodity_only) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2_technical_notes_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that <code>sunflower_oil</code>, <code>palmkernel_oil</code>, <code>manganese_99</code> and <code>jute</code> have quite some missing values. We should be careful about what to do for each case.</p>
<ul>
<li>historical missing can be handled by using already existing data from other sources. If multiple data sources have similar values for most of the time periods, they can be used directly (sunflower oil, palm kernel oil, manganese).</li>
<li>discontinued data: depending on the importance of the product in the index computation, it can be completely dropped (jute).</li>
</ul>
<p>The missingness of prices should be monitored constantly as data sources might change.</p>
<section id="fill-missing-period" class="level2">
<h2 class="anchored" data-anchor-id="fill-missing-period">Fill missing period</h2>
<p>We create a copy of the data for backfilling, in this way we keep track of the original data for comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dcommodity_filled <span class="ot">&lt;-</span> dcommodity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="manganese" class="level3">
<h3 class="anchored" data-anchor-id="manganese">Manganese</h3>
<p>For manganese, we use the historical data from <strong>Metal Bulletin</strong> (6801). This is already processed and saved in <code>prices_2024_compare.rds</code>, so we load the data and retrieve the proper column.</p>
<p>When it comes to backfilling, we use the function <code>rows_patch</code> from <code>dplyr</code>. This function conveniently matches the common column (date time) and fills the missing.</p>
<p>We save it in the <code>dcommodity_filled</code> dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># missing period in the wb data</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>manga_mp <span class="ot">&lt;-</span> <span class="fu">check_missing_period</span>(<span class="at">data =</span> dcommodity, <span class="at">tag =</span> <span class="st">'manganese_99'</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>manga_missing_period <span class="ot">&lt;-</span> manga_mp<span class="sc">$</span>missing_datetime</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># load comparison data</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>dcompare <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">paste0</span>(read_path, dir_val, <span class="st">'prices_2024_compare.rds'</span>))</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># manganese, use the one for 260200.02</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>manga_compare <span class="ot">&lt;-</span> <span class="fu">filter</span>(</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  dcompare, CommodityProduct <span class="sc">==</span> <span class="st">'260200.02'</span> <span class="sc">&amp;</span> dtime <span class="sc">%in%</span> manga_missing_period</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>)<span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="at">manganese_99 =</span> Value, </span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">datetime =</span> dtime)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="co"># select the price in the original data</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>manga_dcommodity <span class="ot">&lt;-</span> <span class="fu">select</span>(dcommodity_filled, </span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>                   manganese_99, datetime)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># patch the same period in the comparison data</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>manga_filled <span class="ot">&lt;-</span> <span class="fu">rows_patch</span>(manga_dcommodity, manga_compare, <span class="at">by =</span> <span class="st">'datetime'</span>)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(manga_filled$manganese_99)</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="co"># replace the filled series in dcommodity</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>dcommodity_filled<span class="sc">$</span>manganese_99 <span class="ot">&lt;-</span> manga_filled<span class="sc">$</span>manganese_99</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sunflower-oil" class="level3">
<h3 class="anchored" data-anchor-id="sunflower-oil">Sunflower oil</h3>
<p>For sunflower oil, we use a comparable historical data from IMF.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>sunflower_dcommodity <span class="ot">&lt;-</span> <span class="fu">select</span>(dcommodity_filled, </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                               sunflower_oil, datetime)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>sunflower_mp <span class="ot">&lt;-</span> <span class="fu">check_missing_period</span>(<span class="at">data =</span> dcommodity, <span class="at">tag =</span> <span class="st">'sunflower_oil'</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>sunflower_missing_period <span class="ot">&lt;-</span> sunflower_mp<span class="sc">$</span>missing_datetime</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># select sunflower oil in the imf data</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>sunflower_imf <span class="ot">&lt;-</span> <span class="fu">select</span>(imf, <span class="at">sunflower_oil =</span> PSUNO, datetime) <span class="sc">|&gt;</span> </span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(datetime <span class="sc">%in%</span> sunflower_missing_period)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># patch the same period in the comparison data</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>sunflower_filled <span class="ot">&lt;-</span> <span class="fu">rows_patch</span>(sunflower_dcommodity, sunflower_imf, <span class="at">by =</span> <span class="st">'datetime'</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># plot(sunflower_filled$sunflower_oil)</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># replace the filled series in dcommodity</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>dcommodity_filled<span class="sc">$</span>sunflower_oil <span class="ot">&lt;-</span> sunflower_filled<span class="sc">$</span>sunflower_oil</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="palm-kernel-oil" class="level3">
<h3 class="anchored" data-anchor-id="palm-kernel-oil">Palm kernel oil</h3>
<p>For this product, we do not have any product that is directly replaceable. We can use palm oil from IMF, which is close enough.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>palmkernel_dcommodity <span class="ot">&lt;-</span> <span class="fu">select</span>(dcommodity_filled, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                                palmkernel_oil, datetime)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>palmkernel_mp <span class="ot">&lt;-</span> <span class="fu">check_missing_period</span>(<span class="at">data =</span> dcommodity, <span class="at">tag =</span> <span class="st">'palmkernel_oil'</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>palmkernel_missing_period <span class="ot">&lt;-</span> palmkernel_mp<span class="sc">$</span>missing_datetime</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># select palm oil in the imf data</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>palm_imf <span class="ot">&lt;-</span> <span class="fu">select</span>(imf, <span class="at">palmkernel_oil =</span> PPOIL, datetime) <span class="sc">|&gt;</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(datetime <span class="sc">%in%</span> palmkernel_missing_period)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="co"># patch the same period in the comparison data</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>palmkernel_filled <span class="ot">&lt;-</span> <span class="fu">rows_patch</span>(palmkernel_dcommodity, palm_imf, <span class="at">by =</span> <span class="st">'datetime'</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co"># replace the filled series in dcommodity</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>dcommodity_filled<span class="sc">$</span>palmkernel_oil <span class="ot">&lt;-</span> palmkernel_filled<span class="sc">$</span>palmkernel_oil</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="price-index-computation" class="level1">
<h1>Price index computation</h1>
<p>This is the step for computing the prices using the weights. One important thing to note is that the <strong>weight matrix does not have the 8 digits code</strong> for individual series, so we need to have one additional step of linking these two tables: <strong>metadata</strong> and <strong>weights</strong>.</p>
<section id="prepare-weights" class="level2">
<h2 class="anchored" data-anchor-id="prepare-weights">Prepare weights</h2>
<section id="weights" class="level3">
<h3 class="anchored" data-anchor-id="weights">Weights</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>weights <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="fu">paste0</span>(read_path, dir_metadata, <span class="st">'weights.xlsx'</span>))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(weights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  index_sort    group subgroup index_description           w           s
1       1001 ALL FOOD     FOOD             Wheat  2206573845 0.001966377
2       1002 ALL FOOD     FOOD             Maize 10035445721 0.008943037
3       1003 ALL FOOD     FOOD              Rice 12086634062 0.010770943
4       1004 ALL FOOD     FOOD             Sugar 18309075031 0.016316040
5       1005 ALL FOOD     FOOD       Bovine meat 10935950196 0.009745517
6       1006 ALL FOOD     FOOD           Bananas  7314470514 0.006518253
  available
1       yes
2       yes
3       yes
4       yes
5       yes
6       yes</code></pre>
</div>
</div>
<p>The content of weight data:</p>
<ul>
<li><code>index_sort</code>: 4-digits ID used to compute price index. Link to <strong>metadata</strong>.</li>
<li><code>group</code>: first level of grouping of commodity</li>
<li><code>subgroup</code>: second level of grouping</li>
<li><code>index_description</code>: description of the index. This does not necessarily link to metadata; however it is indicative to the product used.</li>
<li><code>w</code> and <code>s</code>: numeric values used to compute the weighted sum of the index. <code>s</code> sum up to 1, while <code>w</code> for each product divided by the total sum of w equals to <code>s</code> (hence equivalent).</li>
<li><code>available</code>: indicator of whether this product is available in the data source in 2025.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># shares sum up to 1</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>weights<span class="sc">$</span>s <span class="sc">|&gt;</span> <span class="fu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="combine-weight-with-metadata" class="level3">
<h3 class="anchored" data-anchor-id="combine-weight-with-metadata">Combine weight with metadata</h3>
<p>This step produces a table that provides information that links price series to their weights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(metadata, keep <span class="sc">==</span> <span class="st">'yes'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(index_sort, </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>         series_id, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>         description_short, </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>         within_product_weight,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>         share_scale)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>m <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  index_sort series_id description_short within_product_weight share_scale
1       1005 020100.01              beef                   1.0           1
2       1010 030212.01       fish_salmon                   1.0           1
3       1011 030613.01       shrimps_mex                   1.0           1
4       1006 080300.01         banana_us                   1.0           1
5       1101 090100.03    coffee_arabica                   0.4           1
6       1101 090100.05    coffee_robusta                   0.6           0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ws <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(weights, available <span class="sc">==</span> <span class="st">'yes'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(index_sort, </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>         group, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>         subgroup,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>         index_description,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>         s)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>ws <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  index_sort    group subgroup index_description           s
1       1001 ALL FOOD     FOOD             Wheat 0.001966377
2       1002 ALL FOOD     FOOD             Maize 0.008943037
3       1003 ALL FOOD     FOOD              Rice 0.010770943
4       1004 ALL FOOD     FOOD             Sugar 0.016316040
5       1005 ALL FOOD     FOOD       Bovine meat 0.009745517
6       1006 ALL FOOD     FOOD           Bananas 0.006518253</code></pre>
</div>
</div>
</section>
<section id="within-product-weights" class="level3">
<h3 class="anchored" data-anchor-id="within-product-weights">Within product weights</h3>
<p>Double check how many rows there are. They might be different, but it is not a big problem: we have a mechanism to cope with products that share the same <strong>index sort code</strong>, as explained below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(m), <span class="fu">nrow</span>(ws))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 46 43</code></pre>
</div>
</div>
<p>The within-product weight is defined in the <strong>metadata</strong>. For most products this value is 1, exceptions apply to two products:</p>
<ul>
<li>index sort code 1101: <strong>Coffee</strong> Arabica (090100.03) and Robusta (090100.05) takes up 40% and 60%</li>
<li>index sort code 4201: <strong>Crude oil</strong> - Brent (270900.01) and Dubai (270900.02) takes up 50% each</li>
</ul>
<p>Special case:</p>
<ul>
<li>index sort code 2010: <strong>Rubber</strong> RSS3 (400100.02) and TSR20 (400100.01). We use RSS3 as it is complete, while TSR20 is only available from 1999 in World Bank Data.</li>
</ul>
<p>Now join the selected columns of weight and metadata together by <code>index_sort</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># only 1101 (coffee), 4201 (crude oil) have more frequency</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(m<span class="sc">$</span>index_sort) <span class="sc">|&gt;</span> <span class="fu">sort</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
1001 1002 1003 1004 1005 1006 1008 1010 1011 1102 1103 1201 1202 1203 1204 1206 
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1 
1207 1208 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 3001 3002 3003 3004 
   1    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1 
3005 3006 3007 3008 3009 3101 3102 3103 4001 4101 1101 4201 
   1    1    1    1    1    1    1    1    1    1    2    2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">full_join</span>(m, ws, <span class="at">by =</span> <span class="st">'index_sort'</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(M,<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  index_sort series_id description_short within_product_weight share_scale
1       1005 020100.01              beef                     1           1
2       1010 030212.01       fish_salmon                     1           1
3       1011 030613.01       shrimps_mex                     1           1
     group subgroup index_description           s
1 ALL FOOD     FOOD       Bovine meat 0.009745517
2 ALL FOOD     FOOD              Fish 0.002242046
3 ALL FOOD     FOOD       Crustaceans 0.010791602</code></pre>
</div>
</div>
</section>
</section>
<section id="compute-index" class="level2">
<h2 class="anchored" data-anchor-id="compute-index">Compute index</h2>
<p>Now we compute the index. First we need to base the prices at 2015 as 100: compute the average price for each product for 2015, and merge it back to <strong>M</strong> matrix. These 2015 basis values are used as the denominator when we compute the index.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># call it a different name</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>dprices <span class="ot">&lt;-</span> dcommodity_filled</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>basis_2015 <span class="ot">&lt;-</span> <span class="fu">filter</span>(dprices, year <span class="sc">==</span> <span class="dv">2015</span>) <span class="sc">|&gt;</span> </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(year, period, time, datetime)) <span class="sc">|&gt;</span> </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">apply</span>(<span class="at">MARGIN =</span> <span class="dv">2</span>, mean) </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>basis_2015 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(basis_2015)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>basis_2015<span class="sc">$</span>description_short <span class="ot">&lt;-</span> <span class="fu">rownames</span>(basis_2015)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(basis_2015)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                basis_2015 description_short
beef             4.5591542              beef
banana_us        0.9569142         banana_us
coffee_arabica   3.5260692    coffee_arabica
coffee_robusta   1.9411679    coffee_robusta
tea_mombasa      2.9646806       tea_mombasa
wheat_us       204.4491286          wheat_us</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># merge it to M</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(M, basis_2015, <span class="at">by =</span> <span class="st">'description_short'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Select the relevant columns from the prices (by dropping <code>year, period, time, datetime</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only relevant columns</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>dcwide <span class="ot">&lt;-</span> <span class="fu">select</span>(dprices, <span class="sc">-</span><span class="fu">c</span>(year, period, time, datetime))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># still want to keep track of the time information</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(dcwide) <span class="ot">&lt;-</span> dprices<span class="sc">$</span>datetime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Divide the original values by the 2015 basis, then multiply by their weights. For the special cases (coffee, crude oil), the <em>within_product_weight</em> is used to combine the weighted sum of the two sub-products.</p>
<section id="index-for-one-product-group" class="level3">
<h3 class="anchored" data-anchor-id="index-for-one-product-group">Index for one product group</h3>
<p>UNCTAD has many distinct subgroups for products, hence we need to match the variables for each group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grouping information is in the validation_unctad tab</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>grouping <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="fu">paste0</span>(read_path, dir_metadata, <span class="st">'weights.xlsx'</span>), </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">sheet =</span> <span class="st">'validation_unctad'</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>grouping</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                        unctad_name
1                                  All.groups_Index_Base_2015_Value
2                                    All.food_Index_Base_2015_Value
3                                        Food_Index_Base_2015_Value
4                          Tropical.beverages_Index_Base_2015_Value
5                 Vegetable.oilseeds.and.oils_Index_Base_2015_Value
6                  Agricultural.raw.materials_Index_Base_2015_Value
7                   Minerals..ores.and.metals_Index_Base_2015_Value
8      Minerals..ores.and.non.precious.metals_Index_Base_2015_Value
9                             Precious.metals_Index_Base_2015_Value
10                                      Fuels_Index_Base_2015_Value
11                Tropical.beverages.and.food_Index_Base_2015_Value
12                     All.groups.excl..fuels_Index_Base_2015_Value
13           All.groups.excl..precious.metals_Index_Base_2015_Value
14 All.groups.excl..precious.metals.and.fuels_Index_Base_2015_Value
                              group_name select_group_from
1                                    all           level_1
2                               all_food           level_1
3                                   food           level_2
4                     tropical_beverages           level_2
5                 vegetable_oilseeds_oil           level_2
6              agricultural_raw_material           level_1
7                     minerals_ore_metal           level_1
8  minerals_ore_metal_non_precious_metal           level_2
9                         precious_metal           level_2
10                                 fuels           level_1
11               tropical_beverages_food           level_2
12                        all_excl_fuels           level_1
13               all_excl_precious_metal           level_2
14         all_excl_precious_metal_fuels           level_2</code></pre>
</div>
</div>
<p>Let us test it for the first combination: <strong>all products</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select one combination</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># from 1 to 14</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>cg <span class="ot">&lt;-</span> <span class="fu">query_commodity_group</span>(<span class="at">target_group_info =</span> grouping[<span class="dv">1</span>,])</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>cg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$target_group_info
                       unctad_name group_name select_group_from
1 All.groups_Index_Base_2015_Value        all           level_1

$commodity_groups
[1] "ALL FOOD"                      "AGRICULTURAL RAW MATERIALS"   
[3] "ALL MINERALS, ORES AND METALS" "FUELS"                        

$weight_ref_column
[1] "group"</code></pre>
</div>
</div>
<p>The function <code>compile_index</code> takes in three arguments:</p>
<ul>
<li><code>d_price</code>: the prices for individual products</li>
<li><code>d_weight_unscaled</code>: the weight matrix (after combining metadata)</li>
<li><code>commodity_group</code>: group information used to select and rescale the index</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>index_onegroup <span class="ot">&lt;-</span> <span class="fu">compile_index</span>(<span class="at">d_price =</span> dcwide,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">d_weight_unscaled =</span> M2,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">commodity_group =</span> cg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>compute index for group:  all 
processing product  1 :  beef 
processing product  2 :  fish_salmon 
processing product  3 :  shrimps_mex 
processing product  4 :  banana_us 
processing product  5 :  coffee_arabica 
processing product  6 :  tea_mombasa 
processing product  7 :  wheat_us 
processing product  8 :  maize 
processing product  9 :  rice 
processing product  10 :  soybeans 
processing product  11 :  soybean_meal 
processing product  12 :  cotton 
processing product  13 :  soybean_oil 
processing product  14 :  groundnut_oil 
processing product  15 :  palm_oil 
processing product  16 :  sunflower_oil 
processing product  17 :  coconut_oil 
processing product  18 :  palmkernel_oil 
processing product  19 :  sugar 
processing product  20 :  cocoa 
processing product  21 :  fish_meal 
processing product  22 :  tobacco 
processing product  23 :  phosphate_rock 
processing product  24 :  iron_ore 
processing product  25 :  manganese_99 
processing product  26 :  copper 
processing product  27 :  nickel 
processing product  28 :  aluminium 
processing product  29 :  lead 
processing product  30 :  zinc 
processing product  31 :  tin 
processing product  32 :  silver 
processing product  33 :  coal 
processing product  34 :  crude_oil_brent 
processing product  35 :  naturalgas_index 
processing product  36 :  rubber_rss3 
processing product  37 :  hides 
processing product  38 :  logs_cameroon 
processing product  39 :  sawnwood 
processing product  40 :  plywood 
processing product  41 :  wool_fine 
processing product  42 :  gold 
processing product  43 :  platinum 
processing product  44 :  coffee_robusta 
processing product  45 :  crude_oil_dubai </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(index_onegroup<span class="sc">$</span>index)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1995-01-01 1995-02-01 1995-03-01 1995-04-01 1995-05-01 1995-06-01 
  45.86073   46.50581   46.63123   47.93610   47.44628   46.59248 </code></pre>
</div>
</div>
</section>
<section id="index-for-other-groups" class="level3">
<h3 class="anchored" data-anchor-id="index-for-other-groups">Index for other groups</h3>
<p>Please read through the R code in <code>1_compute_valdiate_index.R</code> section 4.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>