---
title: "World Bank replacements"
description: |
  
#author: "Chi Zhang"
#date: "2025-01-05"
#categories: []
sidebar: false
code-block-bg: false
code-block-border-left: true
format: 
  html:
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false
    highlight-style: gruvbox
---


Motivation: replace the commodity products from their original sources by equivalent items from **World Bank (5110)**.

Abbreviations: 

* WB: World Bank
* MB: Metal Bulletin
* meta: metadata for all commodities

### Data

* `commodity_metadata.xlsx`, the metadata for all commodities. Contains information on the series code, commodity names (short and long), data sources.
  * 79 unique commodity series
  * 21 unique data sources
* `CMO-Historical-Data-Monthly.xlsx` (sheet `Monthly Price`), monthly updated data from World Bank. This is the data we are using to replace Metal Bulletin. 
  * note that this dataset has many more commodities beyond just metals.
* `6801_MetalBulletin_patched.csv`, data collected manually from Metal Bulletin. This is used as baseline and quality check with the automated process from WB.
* ISO 
* ICCO
* Thompson Reuters


## Summary


| Name | Code | Column in WB data| Alternative source | Comment| 
|---|---|---|---|--------|
|Gold | | |MB | OK|
|Copper | | | MB| 260300.01 code has same trend but different values|
|Aluminium | | |MB |OK|
|Silver | | |MB |OK, differ by 100 times |
|Nickel | | |MB |OK |
|Zinc | | | |OK |
|Platinum | |MB | |OK |
|Lead | | |MB | OK|
|Tin | | | MB| OK|
|Manganese | | |MB |Not available in WB|
|Iron |260100.02, 03 |- |TR | TR Only available from 2010.9 for both. WB uses code 02, can directly replace.|














